import os
import json
import logging
from dotenv import load_dotenv
from groq import Groq
load_dotenv()
logger = logging.getLogger("fetal_health")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("GROQ_API_KEY not found in .env")
client = Groq(api_key=GROQ_API_KEY)
def _build_prompt(combined_data: dict) -> str:
    return f"""
You are an expert fetal medicine specialist preparing a professional AI-assisted clinical report.
IMPORTANT
This is an academic Machine Learning project.
The predictions below have ALREADY been generated by ML models.
DO NOT change any prediction.
DO NOT invent patient information.
DO NOT provide a diagnosis.
Explain the ML outputs professionally.
==========================
MODEL RESULTS
==========================
{json.dumps(combined_data, indent=2)}
The field "computed_priority" has already been computed by backend logic.
Use it EXACTLY as monitoring_priority.
Do NOT modify it.
==========================
WRITING STYLE
==========================
Write in professional clinical English.
The report should resemble a hospital summary.
Each section should explain what the ML prediction means instead of simply repeating labels.
When data is unavailable:
Explain that interpretation is limited.
Never guess.
Recommendations should be conservative and evidence-based.
==========================
RETURN FORMAT
==========================
Return ONLY valid JSON.
No markdown.
No explanations.
No code blocks.
JSON format:
{{
    "executive_summary":"",
    "overall_status":"",
    "maternal_analysis":{{
        "summary":"",
        "key_findings":[]
    }},
    "fetal_heart_analysis":{{
        "summary":"",
        "key_findings":[]
    }},
    "ultrasound_analysis":{{
        "summary":"",
        "key_findings":[]
    }},
    "combined_interpretation":"",
    "risk_indicators":[],
    "recommendations":[],
    "monitoring_priority":""
}}
Requirements:
executive_summary:
- 4-6 sentences
- Mention all completed analyses
- Mention unavailable analyses
- Mention monitoring priority
maternal_analysis.summary:
- Explain maternal prediction
- Mention missing information if unavailable
fetal_heart_analysis.summary:
- Explain fetal heart findings
- Mention baseline heart rate if present
ultrasound_analysis.summary:
- Explain ultrasound findings
- Mention unavailable scans if necessary
combined_interpretation:
- Integrate every available module
risk_indicators:
- 3-6 concise items
recommendations:
- 5-8 practical recommendations
- Mention routine follow-up if appropriate
- Mention that AI supports but does not replace clinicians
"""
DEFAULT_REPORT = {
    "executive_summary": "Report generation failed.",
    "overall_status": "Unknown",
    "maternal_analysis": {
        "summary": "Unavailable",
        "key_findings": []
    },
    "fetal_heart_analysis": {
        "summary": "Unavailable",
        "key_findings": []
    },
    "ultrasound_analysis": {
        "summary": "Unavailable",
        "key_findings": []
    },
    "combined_interpretation": "Unavailable.",
    "risk_indicators": [],
    "recommendations": [
        "Please regenerate the report."
    ],
    "monitoring_priority": "Routine"
}
def _clean_json(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.replace("```json", "")
        text = text.replace("```", "")
        text = text.strip()
    return text
def _validate(report: dict, combined_data: dict) -> dict:
    report.setdefault("executive_summary", "")
    report.setdefault("overall_status", "Unknown")
    report.setdefault("maternal_analysis", {})
    report["maternal_analysis"].setdefault("summary", "")
    report["maternal_analysis"].setdefault("key_findings", [])
    report.setdefault("fetal_heart_analysis", {})
    report["fetal_heart_analysis"].setdefault("summary", "")
    report["fetal_heart_analysis"].setdefault("key_findings", [])
    report.setdefault("ultrasound_analysis", {})
    report["ultrasound_analysis"].setdefault("summary", "")
    report["ultrasound_analysis"].setdefault("key_findings", [])
    report.setdefault("combined_interpretation", "")
    report.setdefault("risk_indicators", [])
    report.setdefault("recommendations", [])
    report["monitoring_priority"] = combined_data.get(
        "computed_priority",
        "Routine"
    )
    return report
def generate_ai_report(combined_data: dict) -> dict:
    prompt = _build_prompt(combined_data)
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            temperature=0.2,
            max_completion_tokens=1800,
            messages=[
                {
                    "role": "system",
                    "content":
                        "You are a senior fetal medicine specialist. "
                        "Return ONLY valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )
        report_text = response.choices[0].message.content
        report_text = _clean_json(report_text)
        report = json.loads(report_text)
        return _validate(report, combined_data)
    except Exception as e:
        logger.exception("AI report generation failed")
        fallback = DEFAULT_REPORT.copy()
        fallback["monitoring_priority"] = combined_data.get(
            "computed_priority",
            "Routine"
        )
        return fallback