import os
import json
import logging
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
logger = logging.getLogger("fetal_health")

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError("GROQ_API_KEY not found in .env")

client = Groq(api_key=GROQ_API_KEY)


def _build_prompt(combined_data: dict, has_maternal: bool, has_fhr: bool, has_ultrasound: bool) -> str:
    return f"""
You are an experienced obstetric clinical report assistant preparing a professional AI-assisted clinical report.
IMPORTANT
This is an academic Machine Learning project.
The predictions below have ALREADY been generated by ML models.
DO NOT change any prediction.
DO NOT invent patient information.
DO NOT provide a diagnosis.
Explain the ML outputs professionally.
==========================
MODULE AVAILABILITY
==========================
maternal_result available: {has_maternal}
fhr_result available: {has_fhr}
ultrasound_results available: {has_ultrasound}
IMPORTANT:
Only generate sections for analyses that are available.
Do NOT mention unavailable modules.
If maternal_result is missing, set "maternal_analysis" to null. Do not create it.
If fhr_result is missing, set "fetal_heart_analysis" to null. Do not create it.
If ultrasound_results is empty, set "ultrasound_analysis" to null. Do not create it.
Recommendations must depend ONLY on the available modules listed above.
Do not invent medical findings. Do not hallucinate values.
==========================
MODEL RESULTS
==========================
{json.dumps(combined_data, indent=2)}
The field "computed_priority" has already been computed by backend logic.
Use it EXACTLY as monitoring_priority.
Do NOT modify it.
==========================
WRITING STYLE
==========================
Write in professional clinical English.
The report should resemble a hospital summary.
Each section should explain what the ML prediction means instead of simply repeating labels.
Also explain, where relevant:
- possible health implications
- a simple patient-friendly explanation
- possible risks if recommendations are ignored
Recommendations should be conservative and evidence-based.
==========================
RETURN FORMAT
==========================
Return ONLY valid JSON.
No markdown.
No explanations.
No code blocks.
JSON format:
{{
    "executive_summary":"",
    "overall_status":"",
    "maternal_analysis": null,
    "fetal_heart_analysis": null,
    "ultrasound_analysis": null,
    "combined_interpretation":"",
    "risk_indicators":[],
    "recommendations":[],
    "possible_risks_if_ignored":"",
    "monitoring_priority":""
}}
If a module IS available, replace its null with:
{{
    "summary":"",
    "key_findings":[]
}}
Requirements:
executive_summary:
- 4-6 sentences
- Mention only the analyses that were actually completed
- Do not mention unavailable analyses
- Mention monitoring priority
maternal_analysis.summary (only if available):
- Explain maternal prediction
fetal_heart_analysis.summary (only if available):
- Explain fetal heart findings
- Mention baseline heart rate if present
ultrasound_analysis.summary (only if available):
- Explain ultrasound findings
combined_interpretation:
- Integrate every available module ONLY
- If only one module is available, summarize only that module
- Do not mention missing analyses
risk_indicators:
- 3-6 concise items based only on available findings
recommendations:
- 5-8 practical recommendations based only on available findings
- Mention routine follow-up if appropriate
- Mention that AI supports but does not replace clinicians
possible_risks_if_ignored:
- 1-3 sentences describing plausible consequences of ignoring the recommendations above, based only on available findings
"""


DEFAULT_REPORT = {
    "executive_summary": "",
    "overall_status": "Routine",
    "maternal_analysis": None,
    "fetal_heart_analysis": None,
    "ultrasound_analysis": None,
    "combined_interpretation": "",
    "risk_indicators": [],
    "recommendations": [
        "Please regenerate the report."
    ],
    "possible_risks_if_ignored": "",
    "monitoring_priority": "Routine"
}


def _clean_json(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = text.replace("```json", "")
        text = text.replace("```", "")
        text = text.strip()
    return text


def _validate(report: dict, combined_data: dict) -> dict:
    report.setdefault("executive_summary", "")
    report.setdefault("overall_status", "Unknown")
    report.setdefault("maternal_analysis", None)
    report.setdefault("fetal_heart_analysis", None)
    report.setdefault("ultrasound_analysis", None)
    report.setdefault("combined_interpretation", "")
    report.setdefault("risk_indicators", [])
    report.setdefault("recommendations", [])
    report.setdefault("possible_risks_if_ignored", "")
    report["monitoring_priority"] = combined_data.get(
        "computed_priority",
        "Routine"
    )
    return report


def generate_ai_report(combined_data: dict) -> dict:
    has_maternal = (
        combined_data.get("maternal_analysis", {}).get("prediction") is not None
    )

    has_fhr = (
        combined_data.get("fhr_analysis", {}).get("prediction") is not None
    )

    has_ultrasound = len(
        combined_data.get("ultrasound_analysis", [])
    ) > 0

    prompt = _build_prompt(combined_data, has_maternal, has_fhr, has_ultrasound)
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            temperature=0.2,
            max_completion_tokens=1800,
            messages=[
                {
                    "role": "system",
                    "content":
                        "You are a senior fetal medicine specialist. "
                        "Return ONLY valid JSON."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )
        report_text = response.choices[0].message.content
        report_text = _clean_json(report_text)
        report = json.loads(report_text)
        return _validate(report, combined_data)
    except Exception as e:
        logger.exception("AI report generation failed")
        fallback = DEFAULT_REPORT.copy()
        fallback["monitoring_priority"] = combined_data.get(
            "computed_priority",
            "Routine"
        )
        return fallback