import { notFound } from "next/navigation"
import { getCurrentUser } from "@/lib/auth"
import { sql } from "@/lib/db"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import Link from "next/link"
import { ArrowLeft, AlertTriangle, FileImage, Download } from "lucide-react"

export default async function AssessmentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const user = await getCurrentUser()
  const doctor = user?.doctor

  if (!doctor) return null

  const assessments = await sql`
    SELECT a.*, p.full_name as patient_name, p.pregnancy_week, p.phone as patient_phone
    FROM assessments a
    JOIN patients p ON a.patient_id = p.id
    WHERE a.id = ${id} AND a.doctor_id = ${doctor.id}
  `

  if (assessments.length === 0) {
    notFound()
  }

  const assessment = assessments[0]

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/doctor/assessments">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div className="flex-1">
          <h2 className="text-2xl font-bold text-foreground">Assessment Report</h2>
          <p className="text-muted-foreground">
            {assessment.patient_name} • Week {assessment.pregnancy_week}
          </p>
        </div>
        <Badge
          variant={
            assessment.risk_category === "HIGH"
              ? "destructive"
              : assessment.risk_category === "MEDIUM"
                ? "secondary"
                : assessment.ml_status === "PENDING"
                  ? "outline"
                  : "default"
          }
          className="text-sm"
        >
          {assessment.risk_category || assessment.ml_status}
        </Badge>
      </div>

      {/* AI Disclaimer */}
      <Alert>
        <AlertTriangle className="h-4 w-4" />
        <AlertTitle>AI Analysis Disclaimer</AlertTitle>
        <AlertDescription>
          This analysis is generated by an AI system and should be used as a supplementary tool only. AI can make
          mistakes. Always rely on professional medical judgment for clinical decisions.
        </AlertDescription>
      </Alert>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Vitals Card */}
        <Card>
          <CardHeader>
            <CardTitle>Patient Vitals</CardTitle>
            <CardDescription>Recorded on {new Date(assessment.created_at).toLocaleDateString()}</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Blood Pressure</p>
                <p className="text-lg font-semibold">{assessment.blood_pressure}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Sugar Level</p>
                <p className="text-lg font-semibold">{assessment.sugar_level}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Heart Rate</p>
                <p className="text-lg font-semibold">{assessment.heart_rate}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Weight</p>
                <p className="text-lg font-semibold">{assessment.weight}</p>
              </div>
            </div>
            {assessment.additional_note && (
              <div className="mt-4">
                <p className="text-sm text-muted-foreground">Additional Notes</p>
                <p className="mt-1">{assessment.additional_note}</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Uploaded Files Card */}
        <Card>
          <CardHeader>
            <CardTitle>Uploaded Files</CardTitle>
            <CardDescription>Medical images and charts</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between rounded-lg border border-border p-3">
              <div className="flex items-center gap-3">
                <FileImage className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">X-Ray Image</p>
                  <p className="text-xs text-muted-foreground">{assessment.xray_path}</p>
                </div>
              </div>
              <Button variant="ghost" size="icon">
                <Download className="h-4 w-4" />
              </Button>
            </div>
            <div className="flex items-center justify-between rounded-lg border border-border p-3">
              <div className="flex items-center gap-3">
                <FileImage className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">FHR Chart</p>
                  <p className="text-xs text-muted-foreground">{assessment.fhr_chart_path}</p>
                </div>
              </div>
              <Button variant="ghost" size="icon">
                <Download className="h-4 w-4" />
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* AI Analysis Card */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>AI Analysis Results</CardTitle>
            <CardDescription>Machine learning analysis of submitted data</CardDescription>
          </CardHeader>
          <CardContent>
            {assessment.ml_status === "PENDING" ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="mb-4 h-8 w-8 animate-spin rounded-full border-4 border-primary border-t-transparent" />
                <p className="text-muted-foreground">Analysis in progress...</p>
              </div>
            ) : assessment.ml_status === "FAILED" ? (
              <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Analysis Failed</AlertTitle>
                <AlertDescription>
                  The AI analysis could not be completed. Please try resubmitting the assessment.
                </AlertDescription>
              </Alert>
            ) : (
              <div className="space-y-6">
                {assessment.summary_text && (
                  <div>
                    <h4 className="mb-2 font-medium">Summary</h4>
                    <p className="text-muted-foreground">{assessment.summary_text}</p>
                  </div>
                )}
                {assessment.recommendations && (
                  <div>
                    <h4 className="mb-2 font-medium">Recommendations</h4>
                    <p className="text-muted-foreground">{assessment.recommendations}</p>
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
