import { notFound } from "next/navigation"
import { getCurrentUser } from "@/lib/auth"
import { sql } from "@/lib/db"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import Link from "next/link"
import { ArrowLeft, AlertTriangle, FileImage, Download, MessageCircle } from "lucide-react"

export default async function PatientAssessmentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const user = await getCurrentUser()
  const patient = user?.patient

  if (!patient) return null

  const assessments = await sql`
    SELECT a.*, d.full_name as doctor_name
    FROM assessments a
    LEFT JOIN doctors d ON a.doctor_id = d.id
    WHERE a.id = ${id} AND a.patient_id = ${patient.id}
  `

  if (assessments.length === 0) {
    notFound()
  }

  const assessment = assessments[0]

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/patient/assessments">
            <ArrowLeft className="h-4 w-4" />
          </Link>
        </Button>
        <div className="flex-1">
          <h2 className="text-2xl font-bold text-foreground">Assessment Details</h2>
          <p className="text-muted-foreground">{new Date(assessment.created_at).toLocaleDateString()}</p>
        </div>
        <Badge
          variant={
            assessment.risk_category === "HIGH"
              ? "destructive"
              : assessment.risk_category === "MEDIUM"
                ? "secondary"
                : assessment.ml_status === "PENDING"
                  ? "outline"
                  : "default"
          }
          className="text-sm"
        >
          {assessment.risk_category || assessment.ml_status}
        </Badge>
      </div>

      {/* AI Disclaimer */}
      <Alert>
        <AlertTriangle className="h-4 w-4" />
        <AlertTitle>AI Analysis Disclaimer</AlertTitle>
        <AlertDescription>
          This analysis is generated by an AI system. AI can make mistakes. Always consult with your healthcare provider
          for medical advice and decisions.
        </AlertDescription>
      </Alert>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Vitals Card */}
        <Card>
          <CardHeader>
            <CardTitle>Your Vitals</CardTitle>
            <CardDescription>Health measurements from this assessment</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Blood Pressure</p>
                <p className="text-lg font-semibold">{assessment.blood_pressure}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Sugar Level</p>
                <p className="text-lg font-semibold">{assessment.sugar_level}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Heart Rate</p>
                <p className="text-lg font-semibold">{assessment.heart_rate}</p>
              </div>
              <div className="rounded-lg bg-secondary p-3">
                <p className="text-sm text-muted-foreground">Weight</p>
                <p className="text-lg font-semibold">{assessment.weight}</p>
              </div>
            </div>
            {assessment.additional_note && (
              <div className="mt-4">
                <p className="text-sm text-muted-foreground">Your Notes</p>
                <p className="mt-1">{assessment.additional_note}</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Uploaded Files */}
        <Card>
          <CardHeader>
            <CardTitle>Uploaded Files</CardTitle>
            <CardDescription>Your medical images</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between rounded-lg border border-border p-3">
              <div className="flex items-center gap-3">
                <FileImage className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">Ultrasound Image</p>
                  <p className="text-xs text-muted-foreground">Uploaded successfully</p>
                </div>
              </div>
              <Button variant="ghost" size="icon">
                <Download className="h-4 w-4" />
              </Button>
            </div>
            <div className="flex items-center justify-between rounded-lg border border-border p-3">
              <div className="flex items-center gap-3">
                <FileImage className="h-5 w-5 text-muted-foreground" />
                <div>
                  <p className="text-sm font-medium">FHR Chart</p>
                  <p className="text-xs text-muted-foreground">Uploaded successfully</p>
                </div>
              </div>
              <Button variant="ghost" size="icon">
                <Download className="h-4 w-4" />
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* AI Analysis Results */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>AI Analysis Results</CardTitle>
            <CardDescription>
              {assessment.doctor_name
                ? `Shared with Dr. ${assessment.doctor_name}`
                : "Not linked to a healthcare provider"}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {assessment.ml_status === "PENDING" ? (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <div className="mb-4 h-8 w-8 animate-spin rounded-full border-4 border-[var(--patient-primary)] border-t-transparent" />
                <p className="font-medium">Analysis in progress...</p>
                <p className="text-sm text-muted-foreground">This usually takes a few minutes</p>
              </div>
            ) : assessment.ml_status === "FAILED" ? (
              <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Analysis Failed</AlertTitle>
                <AlertDescription>
                  The AI analysis could not be completed. Please contact support or try submitting a new assessment.
                </AlertDescription>
              </Alert>
            ) : (
              <div className="space-y-6">
                <div className="flex items-center gap-4 rounded-lg bg-secondary p-4">
                  <div
                    className={`flex h-16 w-16 items-center justify-center rounded-full ${
                      assessment.risk_category === "HIGH"
                        ? "bg-destructive/20 text-destructive"
                        : assessment.risk_category === "MEDIUM"
                          ? "bg-[var(--warning)]/20 text-[var(--warning)]"
                          : "bg-[var(--success)]/20 text-[var(--success)]"
                    }`}
                  >
                    <span className="text-2xl font-bold">{assessment.risk_category?.[0]}</span>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Risk Level</p>
                    <p className="text-xl font-semibold">{assessment.risk_category} Risk</p>
                  </div>
                </div>

                {assessment.summary_text && (
                  <div>
                    <h4 className="mb-2 font-medium">Summary</h4>
                    <p className="text-muted-foreground">{assessment.summary_text}</p>
                  </div>
                )}

                {assessment.recommendations && (
                  <div>
                    <h4 className="mb-2 font-medium">Recommendations</h4>
                    <p className="text-muted-foreground">{assessment.recommendations}</p>
                  </div>
                )}

                <div className="flex gap-4">
                  <Button asChild className="bg-[var(--patient-primary)] hover:bg-[var(--patient-primary)]/90">
                    <Link href={`/patient/assessments/${assessment.id}/chat`}>
                      <MessageCircle className="mr-2 h-4 w-4" />
                      Chat with AI
                    </Link>
                  </Button>
                  <Button variant="outline">
                    <Download className="mr-2 h-4 w-4" />
                    Download Report
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
